Deprecated ``_PyErr_ChainExceptions`` in favour of
``_PyErr_ChainExceptions1``.
